# Config for FrankyGo

title = "FrankyGo Config"

[log]
LogLvl = "debug"                    # off|critical|error|warning|notice|info|debug
SearchLogLvl = "debug"              # off|critical|error|warning|notice|info|debug
LogFilePath = "./logs"             # path to logfiles absolut or relative to working directory
#LogFilePath = "D:/_DEV/go/src/github.com/frankkopp/FrankyGo/logs"

[search]
# opening book
UseBook = true
BookPath = "./books"               # absolut or relative to working directory
#BookPath = "D:/_DEV/go/src/github.com/frankkopp/FrankyGo/books"
BookFile = "book.txt"
BookFormat = "Simple"               # Simple | San | Pgn

# TT
UseTT = true
TTSize = 256
UseTTMove = true
UseTTValue = true
UseQSTT = true
UseEvalTT = false

# general search
Ponder = true
UseQuiescence = true
UseQSStandpat = true

UsePVS = true
UseKiller = true

UseIID = true
IIDDepth = 6
IIDReduction = 2

# prunings
UseMDP = true

UseNullMove = true

NmpDepth = 3
NmpReduction = 2

UseLmr = true
LmrDepth = 3
LmrMovesSearched = 3

UseLmp = false

[eval]
UsePawnCache = false # not implemented yet
PawnCacheSize = 64  # not implemented yet

UseLazyEval = true
LazyEvalThreshold = 700

# Evaluation values
Tempo = 30

UseAttacksInEval = false

UseMobility = false
MobilityBonus = 5           # per piece and attacked square

UseAdvancedPieceEval = false
KingRingAttacksBonus = 10   # per piece and attacked king ring square
BishopPairBonus = 20        # once
MinorBehindPawnBonus = 15   # per piece and times game phase
BishopPawnMalus = 5         # per pawn and times ~game phase
BishopCenterAimBonus = 20   # per bishop and times game phase
BishopBlockedMalus = 40     # per bishop
RookOnQueenFileBonus = 6    # per rook
RookOnOpenFileBonus = 25    # per rook and time game phase
RookTrappedMalus = 40       # per rook and time game phase

UseKingEval = false
KingDangerMalus = 50        # number of number of attacker - defender times malus if attacker > defender
KingDefenderBonus = 10      # number of number of defender - attacker times bonus if attacker <= defender
