# Config for FrankyGo

title = "FrankyGo Config"

[log]
LogLvl = "debug"                    # off|critical|error|warning|notice|info|debug
SearchLogLvl = "debug"              # off|critical|error|warning|notice|info|debug
LogFilePath = "../logs"             # path to logfiles absolut or relative to working directory
#LogFilePath = "D:/_DEV/go/src/github.com/frankkopp/FrankyGo/logs"

[search]
# opening book
UseBook = true
BookPath = "../books"               # absolut or relative to working directory
#BookPath = "D:/_DEV/go/src/github.com/frankkopp/FrankyGo/books"
BookFile = "book.txt"
BookFormat = "Simple"               # Simple | San | Pgn

# TT
UseTT = true
TTSize = 256
UseTTMove = true
UseTTValue = true
UseQSTT = true

# general search
Ponder = true
UseQuiescence = true
UseQSStandpat = true
UsePVS = true
UseKiller = true

# prunings
UseMDP = true
UseNullMove = true
NmpDepth = 3
NmpReduction = 2

[eval]
UsePawnCache = true
PawnCacheSize = 64
# Evaluation values
Tempo = 30
