# Config for FrankyGo

title = "FrankyGo Config"

[log]
LogLvl = "debug"             # off|critical|error|warning|notice|info|debug
SearchLogLvl = "debug"       # off|critical|error|warning|notice|info|debug
# TODO ucilogPath

[search]
UseTT = true
TTSize = 256
UseBook = true
# TODO BookPath

[eval]
UsePawnCache = true
PawnCacheSize = 64
